name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build web
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - uses: actions/deploy-pages@v4
